/**:
  ros__parameters:

    # from initialpose (Rviz's 2DPoseEstimate)
    initial_pose_particle_covariance:
      [
        0.2, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.2, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.1,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.1,
      ]
