/**:
  ros__parameters:
    gnss_pose_timeout: 3.0 # [sec]
    stop_check_duration: 3.0 # [sec]

    # from gnss
    gnss_particle_covariance:
      [
        1.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 1.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.01, 0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.01, 0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.01, 0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  10.0,
      ]

    # output
    # initialpose3dの分散
    output_pose_covariance:
      [
        0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
      ]
