/**:
  ros__parameters:
    control:
      type: diagnostic_aggregator/AnalyzerGroup
      path: control
      analyzers:
        control_command_gate:
          type: diagnostic_aggregator/AnalyzerGroup
          path: control_command_gate
          analyzers:
            node_alive_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: node_alive_monitoring
              analyzers:
                heartbeat:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: heartbeat
                  contains: ["vehicle_cmd_gate: heartbeat"]
                  timeout: 1.0

        autonomous_driving:
          type: diagnostic_aggregator/AnalyzerGroup
          path: autonomous_driving
          analyzers:
            node_alive_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: node_alive_monitoring
              analyzers:
                topic_status:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: topic_status
                  contains: [": control_topic_status"]
                  timeout: 1.0

            performance_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: performance_monitoring
              analyzers:
                lane_departure:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: lane_departure
                  contains: [": lane_departure"]
                  timeout: 1.0

                trajectory_deviation:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_deviation
                  contains: [": trajectory_deviation"]
                  timeout: 1.0

                control_state:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: control_state
                  contains: [": control_state"]
                  timeout: 1.0

            lane_monitoring:                           # 追加
              type: diagnostic_aggregator/AnalyzerGroup
              path: lane_monitoring
              analyzers:
                lane_status:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: lane_status
                  contains: ["lane_width_calculator: lane_status"]
                  timeout: 1.0
